/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteservidor;

import java.awt.Frame;
import java.net.InetAddress;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

public class Cliente extends javax.swing.JDialog {

    static Servico servico = null;
    static Servico2 servico2 = null;
    static boolean agencia = false;
    static TelaCliente telaCliente = new TelaCliente();
    String nome = "";
    String numConta = "";
    String saldo = "";
    JPasswordField senha = new JPasswordField();
    Registry registry;
    Registry registry2;

    /**
     * Creates new form Cliente2
     *
     * @param parent
     */
    public Cliente(java.awt.Frame parent, boolean modal) throws RemoteException {
        super(parent, modal);
        initComponents();

        senha.setBounds(6, 105, 100, 30);
        this.add(senha);
        try {
            registry = LocateRegistry.getRegistry(InetAddress.getLocalHost().getHostAddress(), 4000);
            servico = (Servico) registry.lookup("TesteCurry1");
            servico.connectionBanc();
            registry2 = LocateRegistry.getRegistry(InetAddress.getLocalHost().getHostAddress(), 4001);
            servico2 = (Servico2) registry2.lookup("TesteCurry2");
            servico2.connectionBanc();
            System.out.println("Conectado, temporariamente ao servidor 1 e ao servidor 2");
            //servico = (Servico) Naming.lookup(localizacao);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO => " + ex.getMessage());
        }

    }

    public boolean login(String numConta, String senha, boolean agencia) throws SQLException, RemoteException {
        boolean aux = false;
        String senhaBanco = "";
        try {
            if (agencia == true) {
                senhaBanco = servico.senha(numConta);
            }
            if (agencia == false) {
                senhaBanco = servico2.senha(numConta);
            }

            if (senhaBanco.equals(senha)) {
                aux = true;
            }
        } catch (RemoteException ex) {
            System.out.println("erro=>" + ex.getMessage());
        }
        if (aux == true) {
            return true;

        } else {
            return aux;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        num_contaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        agencia1 = new javax.swing.JRadioButton();
        agencia2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Conta Corrente");

        num_contaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_contaTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Senha");

        botaoLogin.setBackground(new java.awt.Color(51, 255, 51));
        botaoLogin.setText("Login");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        agencia1.setText("Agência 1");

        agencia2.setText("Agência 2");
        agencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agencia2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Selecione a Agência");

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel4.setText("Banco Panamericano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_contaText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agencia1)
                    .addComponent(agencia2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_contaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agencia1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agencia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        try {
            if (agencia1.isSelected() == true) {
                agencia = true;
                try {
                    registry = LocateRegistry.getRegistry(InetAddress.getLocalHost().getHostAddress(), 4000);
                    servico = (Servico) registry.lookup("TesteCurry1");
                    servico.connectionBanc();
                    System.out.println("Estou conectado, Servidor 1");
                    //servico = (Servico) Naming.lookup(localizacao);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERRO => " + ex.getMessage());
                }
                try {
                    String teste = num_contaText.getText();

                    if (!this.num_contaText.getText().trim().equals("")) {

                        if (this.login(this.num_contaText.getText(), this.senha.getText(), true) == true) {

                            this.dispose();
                            telaCliente.setClienteNome(servico.nome(this.num_contaText.getText()));
                            telaCliente.setSaldoText(servico.saldo(this.num_contaText.getText()));
                            telaCliente.setNumContaText(this.num_contaText.getText());
                            telaCliente.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Dados incorretos");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Algum campo esta nulo");
                        return;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (agencia2.isSelected() == true) {
                agencia = false;
                
                try {
                    registry = LocateRegistry.getRegistry(InetAddress.getLocalHost().getHostAddress(), 4001);
                    servico2 = (Servico2) registry.lookup("TesteCurry2");
                    servico2.connectionBanc();
                    System.out.println("Conectado, Servidor 2");
                    //servico = (Servico) Naming.lookup(localizacao);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERRO => " + ex.getMessage());
                }
                try {
                    String teste = num_contaText.getText();
                    if (!this.num_contaText.getText().trim().equals("")) {
                        if (this.login(this.num_contaText.getText(), this.senha.getText(), false) == true) {
                            this.dispose();
                            telaCliente.setClienteNome(servico2.nome(this.num_contaText.getText()));
                            telaCliente.setSaldoText(servico2.saldo(this.num_contaText.getText()));
                            telaCliente.setNumContaText(this.num_contaText.getText());
                            telaCliente.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Dados incorretos");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Algum campo esta nulo");
                        return;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (!this.agencia1.isSelected() && !this.agencia2.isSelected()) {
                JOptionPane.showMessageDialog(null, "Determine a sua agência");

            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_botaoLoginActionPerformed

    private void num_contaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_contaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_contaTextActionPerformed

    private void agencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agencia2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente dialog = null;
                try {
                    dialog = new Cliente(new javax.swing.JFrame(), true);
                } catch (RemoteException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agencia1;
    private javax.swing.JRadioButton agencia2;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField num_contaText;
    // End of variables declaration//GEN-END:variables
}
